FROM node:17-buster-slim

WORKDIR /app

# RUN npm install --save react-router-dom
# RUN npm install --save prop-types
# RUN npm install -g firebase (←firebaseも使いたいので記述)
# RUN npm install -g firebase-tools (←firebaseCLI)))
